### ISSUE TITLE
Request a github release and license file

### ISSUE THREAD

**Issue by Takadonet** [Phelimb/cbg#18]
It is possible to have an official github release? Reason being is that I wish to create a bioconda recipe and they prefer to tie version to a release instead of a commit. https://bioconda.github.io/  Having a bioconda recipe make it easier for others to install and able to migrate to Galaxy platform as well (http://usegalaxy.org/)

One other thing is to have a license file. Hopefully open source? 

Cheers

**Comment by Phelimb** [comment]
Thanks!

Release here - https://github.com/Phelimb/cbg/releases/tag/v0.1.5

Let me know if you have any other problems creating the conda recipe.
